# Generated by Django 5.1a1 on 2024-05-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
