# Generated by Django 5.1a1 on 2024-05-26 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
