# Generated by Django 5.1a1 on 2024-05-27 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serin_zenith_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textgeneration',
            name='advanced_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serin_zenith_settings.advancedsettings'),
        ),
        migrations.AlterField(
            model_name='textgeneration',
            name='contextual_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serin_zenith_settings.contextualsettings'),
        ),
        migrations.AlterField(
            model_name='textgeneration',
            name='dynamic_adjustments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serin_zenith_settings.dynamicadjustments'),
        ),
        migrations.AlterField(
            model_name='textgeneration',
            name='generation_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serin_zenith_settings.generationsettings'),
        ),
        migrations.AlterField(
            model_name='textgeneration',
            name='penalties_and_filters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serin_zenith_settings.penaltiesandfilters'),
        ),
        migrations.AlterField(
            model_name='textgeneration',
            name='sampling_parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serin_zenith_settings.samplingparameters'),
        ),
    ]
